/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author RJMV
 */

import java.sql.*;
import javax.swing.table.DefaultTableModel;
import dao.Conexion;

public class DashboardView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardView.class.getName());

    /**
     * Creates new form DashboardView
     */
    public DashboardView() {
        initComponents();
        setLocationRelativeTo(null);
        cargarDatos();
        cargarDashboard();
    }
    
    public void cargarDatos() {
        try {
            Connection conn = Conexion.getConnection();
            Statement stmt = conn.createStatement();

            ResultSet rs1 = stmt.executeQuery("SELECT COUNT(*) as total FROM habitante");
            if (rs1.next()) {
                lblTotalHabitantes.setText("Habitantes: " + rs1.getInt("total"));
            }

            ResultSet rs2 = stmt.executeQuery("SELECT COUNT(*) as total FROM vivienda");
            if (rs2.next()) {
                lblTotalViviendas.setText("Viviendas: " + rs2.getInt("total"));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void cargarDashboard() {
        try {
            Connection conn = Conexion.getConnection();
            Statement stmt = conn.createStatement();

            // 🔹 TOTAL HABITANTES
            ResultSet rs1 = stmt.executeQuery("SELECT COUNT(*) as total FROM habitante");
            if (rs1.next()) {
                lblTotalHabitantes.setText(rs1.getInt("total") + "");
            }

            // 🔹 TOTAL VIVIENDAS
            ResultSet rs2 = stmt.executeQuery("SELECT COUNT(*) as total FROM vivienda");
            if (rs2.next()) {
                lblTotalViviendas.setText(rs2.getInt("total") + "");
            }

            // 🔹 HABITANTES POR MUNICIPIO
            ResultSet rs3 = stmt.executeQuery(
                "SELECT m.nombre, COUNT(h.id) as total " +
                "FROM habitante h " +
                "JOIN vivienda v ON h.vivienda_id = v.id " +
                "JOIN municipio m ON v.municipio_id = m.id " +
                "GROUP BY m.nombre"
            );

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Municipio");
            model.addColumn("Habitantes");

            while (rs3.next()) {
                model.addRow(new Object[]{
                    rs3.getString("nombre"),
                    rs3.getInt("total")
                });
            }

            tablaMunicipios.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTotalHabitantes = new javax.swing.JLabel();
        lblTotalViviendas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMunicipios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Dashboard Censo INEGI");

        lblTotalHabitantes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalHabitantes.setText("jLabel2");

        lblTotalViviendas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalViviendas.setText("jLabel3");

        tablaMunicipios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaMunicipios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalViviendas)
                            .addComponent(lblTotalHabitantes))))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalHabitantes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalViviendas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalHabitantes;
    private javax.swing.JLabel lblTotalViviendas;
    private javax.swing.JTable tablaMunicipios;
    // End of variables declaration//GEN-END:variables
}
